server:
  port: 9090

logging:
  config: classpath:logback.xml

jdbc:
  url: jdbc:sqlite:/data/ticket_inn.db
  busyTimeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatisConfig.xml
  type-handlers-package: org.metro.dao.handler

spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB