server:
  port: 9090
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /ticket-inn
#  undertow:
#    io-threads: 4
#    worker-threads: 8

logging:
  config: classpath:logback.xml

oss:
  storage-path: /data/oss

cache:
  prefix-dir: /data/cache

jdbc:
  url: jdbc:sqlite:/data/sqlite/ticket_inn.db
  busy-timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: org.metro.dao.handler

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
